name: simple_3d_renderer
description: Sp3dObj renderer. Includes simple cameras, lights, worlds, and more.
version: 15.0.0
repository: https://github.com/MasahideMori-SimpleAppli/simple_3d_renderer

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^10.0.0
  util_simple_3d: ^7.0.0

dependency_overrides:
  simple_3d:
    git:
      url: https://github.com/LeGoffMael/simple_3d
      ref: feat/sp3d_paint_style

dev_dependencies:
  flutter_test:
    sdk: flutter